version: "3.9"

services:
  db:
    image: postgres:15
    container_name: todo_postgres
    restart: always
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - todo_data:/var/lib/postgresql/data

volumes:
  todo_data:
